### PR TITLE
ci(node): set node 8 to 8.3 and add node 12

### LINKED ISSUE #128: Test in Node 8.3 and Node 12
We are currently testing in Node 8 and 10:

https://github.com/semantic-release/commit-analyzer/blob/a71866f37d2165c467be63360143d9d56b419dfc/.travis.yml#L2-L4

We want to test in 8.3 explicitly as it is currently the minimal Node version supported by semantic-release. And we want to start testing in Node 12 as it is the latest stable version.

### PR DESCRIPTION
**Pull request by mehrad-rafigh**
This closes #128

### CODE REVIEW

**Comment by mehrad-rafigh** [comment]
@gr2m should we update all packages in semantic-release to utilise node 8.3, 10 and 12?

**Comment by gr2m** [comment]
That would be great, yes

**Review by gr2m — APPROVED** [review]

**Comment by mehrad-rafigh** [comment]
Awesome. So I already started and will take a look and list the others here which I would update appropriately. Sounds good @gr2m?

**Comment by gr2m** [comment]
sounds great, cheers

**Pull request merged**
