### PR TITLE
Handle squash merges

### PR DESCRIPTION
**Pull request by jwalton**
See discussion https://github.com/semantic-release/commit-analyzer/issues/65 and https://github.com/semantic-release/semantic-release/issues/792.

This makes it so commit-analyzer parses commit messages of the form:

```
Squashed commit of the following:

commit 74e6b0087331e5947fd8ba388e75d4d1900dfd44
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:21:50 2018 -0400

    fix: More fixes

commit b894885ae467975226e81080a35625d247796960
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:13:25 2018 -0400

    fix: Fix
```

as a collection of individual commits, rather than as a single commit message.  Note that in order to be broken up, the commit *must* start with the line "Squashed commit of the following:", and be followed by one or more "commit, author. date, indentented-body" groups.  If the commit does not follow this format exactly, then we'll treat the entire commit message as a single commit (exactly like it used to be).

* If you accidentally squash-merge a "feat" from github, this will now correctly produce a "minor" release instead of a "patch" release.
* Note that if you modify the first line (change it to "fix: blahblahblah", for example), then we'll treat the entire commit as a single commit, and use a "patch" release (unless "BREAKING CHANGE" appears anywhere in one of the child commits, and then we'll treat it as "major" - this is a bit sketchy, but is unchanged from current behavior.)  You can still edit squash merges to fix things, in fact...
* If you modify individual messages inside the squash merge, but leave the "Squashed commit of the following:" at the top, then we'll scan individual commits within the squash merge with your changes, allowing you fine grained control editing squash merges.

Note the log explicitly identifies commits that were parsed from a squash merge:

screen shot 2018-05-18 at 7 54 13 am

### CODE REVIEW

**Comment by Hotalenw** [comment]
Hello, I am attempting to use this and cant seem to get the commits in the squash merge to be in the right format. Any tips? I have semantic-release set up and working great just need it to work for squash merges. I know this is a closed PR I just cant find this topic anywhere else.

**Comment by rehangit** [comment]
Why was this PR closed? With some modification this could be a great idea! 

Squashing commits with single headline message is a popular practice to produce a sanitised commit history in master branch with jira ticket numbers as prefixes or some other format. We use it in our team extensively. It provides a more sensible commit history once a long time has passed. 

If the hash symbol with number (#NNN) at the end of the commit message is used as trigger to include the commit message to be analysed for commit history it will work really well with Github style squashed merges.

**Comment by good-idea** [comment]
I'd also love to know why this was closed ~ currently, the only way to get proper versioning is to manually edit PR commit messages to A) match the conventional-commit format, and B) ensure that the type is the "highest" one in the branch's commit history.

Having a squashed commit message that looks like this:

```
Squashed commit of the following:

commit 74e6b0087331e5947fd8ba388e75d4d1900dfd44
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:21:50 2018 -0400

    fix: More fixes

commit b894885ae467975226e81080a35625d247796960
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:13:25 2018 -0400

    fix: Fix
```

trigger a `fix` bump, and this:

```
Squashed commit of the following:

commit 74e6b0087331e5947fd8ba388e75d4d1900dfd44
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:21:50 2018 -0400

    fix: More fixes

commit b894885ae467975226e81080a35625d247796960
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:13:25 2018 -0400

    fix: Fix

commit 74e6b0087331e5947fd8ba388e75d4d1900dfd44
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:21:50 2018 -0400

    feat: Add a feature

commit b894885ae467975226e81080a35625d247796960
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:13:25 2018 -0400

    fix: Fix
    
commit b894885ae467975226e81080a35625d247796960
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:13:25 2018 -0400

    chore: some chore
```

triggering a `feat` bump seems sensible.

any reasons why not?

**Comment by incuedAA** [comment]
We're gonna drop using semantic release due to this issue. Squash commits are very common, and the fact that #66 got dropped tells me there are no plans of this being supported. It's making our commit history messy and hard to track.

**Comment by romap0** [comment]
Hi guys. I've implemented a tiny wrapper for commit-analyzer and release-notes-generator which works with squashed MRs.
You can check it out: [semantic-release-unsquash](https://github.com/romap0/semantic-release-unsquash)
I've tested it on my project and it works like a charm

**Pull request closed without merging**
