### PR TITLE
fix: Accept undefined options and commits array

### PR DESCRIPTION
**Pull request by pvdlg**
Should resolve semantic-release/semantic-release#436

### CODE REVIEW

**Comment by gr2m** [comment]
can you elaborate on what the underlying problem is and how this resolves it, so we have it for future reference?

**Comment by pvdlg** [comment]
Sure it seems that `semantic-release` call the plugins passing the pluginConfig parameter as `undefined` if no options is. I'm not sure if it's something specific to the test case (the test are really difficult to figure out for me) or if there is a case in which `semantic-release` can actually do that.

My understand was that due to [index.js#L26](https://github.com/semantic-release/semantic-release/blob/caribou/src/index.js#L26), `options.analyzeCommits` should always be an object and never be undefined. But I might be wrong.

Anyway it's probably better for the plugin to handle the case of `pluginOptions` being `undefined` the same as if it was equal to `{}`.

**Comment by pvdlg** [comment]
It seems codecov is not working and I don't have the proper access. I sent you a request to let me access codecov for the orga.

**Comment by gr2m** [comment]
I’ve granted access to codecov

**Comment by gr2m** [comment]
This seems wrong to me. defaulting pluginConfig to `{}` is okay, but wouldn't other plugins fail as well? 

The fact that no commits array is being passed doesn’t make sense though, does it? I think there is another problem here. I’d like to further investigate it. I can have a look myself over the next weekend, if you could have a look yourself, that’d be graet

**Comment by pvdlg** [comment]
I added the case for no commit just as a safety. It was not failing. I can remove it.
It seems `semantic-release` can pass `undefined` for `pluginConfig`  for each default plugins (and only the default ones). It hasn't been detected before because:
- The previous default plugins do not use `pluginConfig`
- The new plugins use `pluginConfig` and before the default the plugin configuration was mandatory
- We don't see the error in `release-notes-generator` because there is integration test in `semantic-release` for the `post` command

**Comment by gr2m** [comment]
Okay the undefined `pluginConfig` makes sense. I would not default the commits array though, can change that?

**Comment by pvdlg** [comment]
> Okay the undefined pluginConfig makes sense. I would not default the commits array though, can change that?

Sure. I just pushed the change

**Pull request merged**
